version: '3'
services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root
    volumes:
      - .:/root
    ports:
      - "8501:8501"
    command:
      - python3
      - -m
      - streamlit
      - run
      - chatbot_sample.py